language: android

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android

android:
  components:
    - build-tools-23.0.1
    - android-23

env:
  global:
  - secure: "N65Gr043MKcOCsRGTaG4Agk+MxTV/QXUU753Z7jgLqaz6oGugtb25oh7fuQ5OrSuF/XV2AXJaM03++2Wa3Xadp4CCA/ciJUMFhmy5KY/PLzpnNtFO0HY0B1IPS79fvsLKNnMaQTW46hnQWIvsXCfTjqzXIZ612ZcQxFdYZEUpns="
  - secure: "W6QGZAbSdKkLJQ53hDs5LXRNNCQnv18W40/h2vkEdoImIJ3pZX/gTbycmS0D3x7Ev8BsgjH0/jaK+BeTRmABBs2U7jld7XN690O3dkHTSONRVcRk9litCpvBDnzlt6EaMjvYZSzJ4YPBefG1MFtw+dJkZ5sO6k1J81zaOAXSI90="
  - JAVA_OPTS=-XX:MaxPermSize=1024m

notifications:
  email: false

install:
- TERM=dumb ./gradlew -q -s clean assemble

script:
- TERM=dumb ./gradlew -s --continue check jacocoTestReport install integrationTests

after_success:
- bash <(curl -s https://codecov.io/bash)
- ./scripts/deploy_to_maven.sh

notifications:
  email: false
  
